apiVersion: batch/v1
kind: CronJob
metadata:
  name: ticker
spec:
  schedule: "0 22 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ticker
            image: 576640153544.dkr.ecr.us-east-1.amazonaws.com/ticker:36f8f3f3329e8db5b654318e7622035484ef8038
            imagePullPolicy: IfNotPresent
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: snsticker
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: snsticker
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: snsticker
                  key: AWS_DEFAULT_REGION
          imagePullSecrets:
            - name: awsecr-cred
          restartPolicy: OnFailure
